trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


variables:
  imageName: '$(yourImageName):$(Build.BuildId)'
  registryName: '$(registryName)'
  registryUsername: '$(registryUsername)'
  registryPassword: '$(registryPassword)'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python hello_world.py
  displayName: 'Run Hello World Script'

- script: docker build -t $(registryName)/$(imageName) .
  displayName: 'Docker Build'

- script: |
    docker login $(registryName) -u $(registryUsername) -p $(registryPassword)
    docker push $(registryName)/$(imageName)
  displayName: 'Docker Push'





