trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


variables:
  imageName: 'helloworld:$(Build.BuildId)'
  registryName: 'acrforazuredevopspipelines.azurecr.io'
  registryUsername: 'acrforazuredevopspipelines'
  registryPassword: '6L03Z/bSkkeHreu6gPGBnocHZZUgnWs6tj1cDRigtV+ACRACYe1y'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python hello_world.py
  displayName: 'Run Hello World Script'

- script: docker build -t $(registryName)/$(imageName) .
  displayName: 'Docker Build'

- script: |
    docker login $(registryName) -u $(registryUsername) -p $(registryPassword)
    docker push $(registryName)/$(imageName)
  displayName: 'Docker Push'





