trigger:
- main

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python hello_world.py
  displayName: 'Run Hello World Script'

- script: docker build -t $(REGISTRYNAME)/$(YOURIMAGENAME):$(Build.BuildId) .
  displayName: 'Docker Build'

- script: |
    docker login $(REGISTRYNAME) -u $(REGISTRYUSERNAME) -p $(REGISTRYPASSWORD)
    docker push $(REGISTRYNAME)/$(YOURIMAGENAME):$(Build.BuildId)
  displayName: 'Docker Push'

