trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:


# Build and Push Docker Image
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'Azure-Container-Registry-Service-Connection'
    repository: 'ACR-For-Azure-DevOps-Pipelines'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'


